# Generated by Django 4.2.13 on 2024-07-08 08:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Cabriolet', 'Cabriolet'), ('Hatchback', 'Hatchback'), ('Station Wagon', 'Station Wagon'), ('Minivan', 'Minivan'), ('SUV', 'SUV'), ('Pickup Truck', 'Pickup Truck')], max_length=15)),
                ('year', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('doors', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], default='petrol', max_length=8)),
                ('transmission', models.CharField(choices=[('MT', 'Manual Transmission'), ('AT', 'Automatic Transmission')], max_length=2)),
                ('air_conditioning', models.BooleanField()),
                ('navigation', models.BooleanField()),
                ('availability', models.BooleanField(default=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
        ),
    ]
