# Generated by Django 4.2.13 on 2024-07-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='air_conditioning',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=8),
        ),
        migrations.AlterField(
            model_name='car',
            name='navigation',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('MT', 'Manual'), ('AT', 'Automatic')], max_length=2),
        ),
    ]
