# Generated by Django 4.2.13 on 2024-08-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_air_conditioning_alter_car_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['make', 'model']},
        ),
    ]
