# Generated by Django 4.2.13 on 2024-07-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('google_map_link', models.URLField()),
                ('opening_time', models.TimeField(default='08:00')),
                ('closing_time', models.TimeField(default='20:00')),
            ],
        ),
    ]
