# Generated by Django 4.2.13 on 2024-07-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_remove_office_address_office_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Latitude coordinate', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Longitude coordinate', max_digits=30, null=True),
        ),
    ]
