# Generated by Django 4.2.13 on 2024-07-08 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_alter_car_air_conditioning_alter_car_fuel_type_and_more'),
        ('offices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pick_up_time', models.TimeField(blank=True, choices=[], null=True)),
                ('drop_off_time', models.TimeField(blank=True, choices=[], null=True)),
                ('child_seat', models.BooleanField(default=False)),
                ('child_seat_option', models.CharField(blank=True, choices=[('0-9 kg', '0-9 kg'), ('9-18 kg', '9-18 kg'), ('booster', 'Booster')], max_length=20, null=True)),
                ('extra_insurance', models.BooleanField(default=False)),
                ('rules_agreement', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='confirmed', max_length=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('pickup_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_office', to='offices.office')),
                ('return_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_office', to='offices.office')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
