# Generated by Django 4.2.13 on 2024-07-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_phone_number_alter_booking_drop_off_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default=1111, max_length=254),
            preserve_default=False,
        ),
    ]
