# Generated by Django 4.2.13 on 2024-07-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rental_days',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
