# Generated by Django 4.2.13 on 2024-07-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_first_name_alter_booking_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='review_left',
            field=models.BooleanField(default=False),
        ),
    ]
