# Generated by Django 4.2.13 on 2024-08-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_options_booking_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
    ]
